# Makefile

### UTILS
CONFIG = Makefile Doxyfile

clean: 
	rm -f *~ \#* css *.html *.js *.map *.md5 *.png *.svg

cleanall: 
	-make clean; 

## display asaxPages 
GITPAGES_DIR=/Users/arim/myLocal/asaxPages/
doc.pack: 
	scp -r $(HTMLDIR)/  $(GITPAGES_DIR)
	cd $(GITPAGES_DIR); git add . ; git commit -m "reflesh pages"; git push 

doc.clean: $(HTMLDIR)/
	rm -rf $(HTMLDIR)/*

htmljavadoc:
	make javadoc
	open $(HTMLDIR)/index.html

## EOF

